ALTER TABLE categories ALTER COLUMN description TYPE VARCHAR(200);
ALTER TABLE categories ALTER COLUMN name TYPE VARCHAR(100);

ALTER TABLE courses ALTER COLUMN description TYPE VARCHAR(200);
ALTER TABLE courses ALTER COLUMN status TYPE VARCHAR(255);
ALTER TABLE courses ALTER COLUMN title TYPE VARCHAR(100);

ALTER TABLE lessons ALTER COLUMN description TYPE VARCHAR(200);
ALTER TABLE lessons ALTER COLUMN lesson_url TYPE VARCHAR(500);
ALTER TABLE lessons ALTER COLUMN title TYPE VARCHAR(100);

ALTER TABLE modules ALTER COLUMN description TYPE VARCHAR(200);
ALTER TABLE modules ALTER COLUMN title TYPE VARCHAR(100);

ALTER TABLE study_sessions ALTER COLUMN notes TYPE VARCHAR(200);
ALTER TABLE users ALTER COLUMN role TYPE VARCHAR(255);

ALTER TABLE lesson_progress DROP CONSTRAINT IF EXISTS UK7lok1iwll7jsobapv1rmr563;
ALTER TABLE lesson_progress ADD CONSTRAINT UK7lok1iwll7jsobapv1rmr563 UNIQUE (user_id, lesson_id);